name: Deploy to Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: ${{ vars.SITE_URL}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Supabase Setup
        uses: supabase/setup-cli@v1
        with:
          version: 2.33.7

      - name: Supabase Deploy
        env:
          SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }} 
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PERSONAL_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SITE_URL: ${{ vars.SITE_URL }}
          RESEND_ENABLED: ${{ vars.RESEND_ENABLED }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          supabase link --project-ref ${{ vars.SUPABASE_PROJECT_REF }}
          supabase config push
          supabase db push --include-seed